### ISSUE TITLE
REVIGO.csv file could not be converted by CirGO

### ISSUE THREAD

**Issue by Sashkow** [IrinaVKuznetsova/CirGO#3]
Apparently REVIGO has changed format of the file that is obtained by pressing Export results to text table (CSV) in the web interface. Representative colum in revigo.csv file now lists GO ids instead of of textual descriptions of the ontology categories.

CirGO Gui returns error "File could not be converted. Please check if the file exists and if the file format is correct!" when fed with a revigo.csv file. Here is the file REVIGO file [example](https://github.com/Sashkow/cir-go-issue/blob/main/REVIGO.csv)

**Comment by Sashkow** [comment]
I've modified csv file conversion code for compatibility with REVIGO but I do not know whether it broke compatibility with other platforms. [Fork](https://github.com/Sashkow/CirGO)

**Comment by IrinaVKuznetsova** [comment]
Dear CirGO users, 

REVIGO has't changed the input file format. The CSV file should be downloaded from the "TreeMap" tab.
![image](https://user-images.githubusercontent.com/37644569/102712341-714c9180-42fb-11eb-8f33-4378992af3fb.png)

Hope this helps

**Comment by nathanerank** [comment]
I installed CirGO on a Mac running Catalina, and I got the GUI to run but I cannot get it to convert the CSV file. I tried to use your sample file Example_REVIGO_Input_BP and that won't work either. I am attaching the version that I am trying to convert. 
[Cluster 0 revigo biological process pvalue cirgo.pdf](https://github.com/IrinaVKuznetsova/CirGO/files/6238359/Cluster.0.revigo.biological.process.pvalue.cirgo.pdf)

**Comment by nathanerank** [comment]
We also tried the same thing on a different Mac with a different OS, and had exactly the same problems Cirgo won't run and the error message states that the file can't be converted.

**Comment by Sashkow** [comment]
@nathanerank Your file appears to be pdf, not csv. If you are working from Excel, you can save your .xlsx spreadsheet file as a comma separated file.

**Comment by nathanerank** [comment]
I was unable to load the csv onto this page. My files are csv files, not PDF.

**Comment by Sashkow** [comment]
Rownames are missing in your csv. Rownames should match the example.

**Comment by Gurlaz** [comment]
Hello,

I am having the same issue. I am running CirGO on MacOS High Sierra. GUI version loads successfully. A .csv file was obtained from Revigo tree map tab and an automatically generated file name confirms that too. When I click on visualize I get an error "File could not be converted. Please check the file format and it's content!"

My input file have 146 rows and 7 columns named : "TermID | Name | Frequency | Value | Uniqueness | Dispensability | Representative".

Was anyone above able to solve this issue?

Thank you!

**Comment by Gurlaz** [comment]
> Hello,
> 
> I am having the same issue. I am running CirGO on MacOS High Sierra. GUI version loads successfully. A .csv file was obtained from Revigo tree map tab and an automatically generated file name confirms that too. When I click on visualize I get an error "File could not be converted. Please check the file format and it's content!"
> 
> My input file have 146 rows and 7 columns named : "TermID | Name | Frequency | Value | Uniqueness | Dispensability | Representative".
> 
> I even used example file "Example_REVIGO_Input_BP.csv" and it gave me the same error.
> 
> Was anyone above able to solve this issue?
> 
> Thank you!

Command Line option is also giving a similar error:
```
Opening input file: Example_REVIGO_Input_BP.csv
File could not be converted. Please check if the file exists and if the file format is correct!
Traceback (most recent call last):
  File "/Users/CirGO/Py3+/CirGO_Wind_Unix/CirGO.py", line 360, in main
    CirGoFileConversion.ConvertToThreeCoulmnsInput(args.inputFile, fn+ "_converted.csv")
  File "/Users/CirGO/Py3+/CirGO_Wind_Unix/CirGoFileConversion.py", line 60, in ConvertToThreeCoulmnsInput
    while (x[0].startswith("%")):
IndexError: list index out of range
```

**Comment by IrinaVKuznetsova** [comment]
>Hi [Gurlaz](https://github.com/Gurlaz),

Can you please check that your Python version is 3.7+ in your environment. Below is the command to check:
`conda list `

Also, please check input file format. If you open your input file with Notepad, does it look similar to this?

```
% WARNING - This is exported REVIGO data useful only for the specific purpose of constructing a TreeMap visualization.,,,,,,
% Do not use this table as a general list of non-redundant GO categories, as it sets an extremely permissive ,,,,,
% threshold to detect redundancies (c=0.10) and fill the 'representative' column, while normally c>=0.4 is recommended.,,,,,
% To export a reduced-redundancy set of GO terms, go to the Scatterplot & Table tab, and export to CSV from there.,,,,
term_ID,description,frequencyInDb,log10pvalue,uniqueness,dispensability,representative
GO:0002376,immune system process,0.60%,-7.6615,0.994,0,immune system process
GO:0006950,response to stress,4.58%,-24.6003,0.937,0,response to stress
GO:1901700,response to oxygen-containing compound,0.50%,-9.8297,0.943,0.683,response to stress
```

**Comment by konetom** [comment]
Dear @IrinaVKuznetsova, please refresh your CirGoFileConversion.py according to the current format of comment lines in the Revigo csv file, the comment lines start with # sign, not with %.

<pre>
line 68:    # skip eventual comment lines that are contained inside the csv file
line 69:    if not row[0].startswith("%"):
</pre>

Best regards

**Comment by Ruiqi-CUB** [comment]
How did everyone get the Revigo csv? I can only see the download tsv under the Tree Map tab. 
![image](https://user-images.githubusercontent.com/46695842/217708476-e622cb16-0554-48fe-abee-94015df1cd39.png)

**Comment by konetom** [comment]
> How did everyone get the Revigo csv? I can only see the download tsv under the Tree Map tab. ![image](https://user-images.githubusercontent.com/46695842/217708476-e622cb16-0554-48fe-abee-94015df1cd39.png)

Just download the TSV and use it as the input.

**Comment by zhangwenda0518** [comment]
The latest revigo uses tab splitting, so the converted script CirGoFileConversion.py, line 56, InputFileReader = CSV. Reader (InputFile, Delimiter =',') should be modified to InputFileReader = CSV. Reader (InputFile, Delimiter =' \ t').

**Comment by zhangwenda0518** [comment]
At the same time, the 60th line while (x[0].startswith("% ")):
It should be changed to 60 while (x[0].startswith("# ")):

**Comment by RaquelRodVaz** [comment]
Hello, when I download the TSV from REVIGO and try to use it with CIRGO, it gives me an error. From what I've seen, they changed the TSV format, and when I download the TSV, the p-values don't appear, and that might be what's causing the error. Have you found a solution for this? Thank you very much.
