### ISSUE TITLE
Cannot load backend 'TkAgg' 

### ISSUE THREAD

**Issue by babramso** [IrinaVKuznetsova/CirGO#5]
I'm trying to run this on Ubuntu in WSL.  I followed the install for py3.  Any help would be appreciated.

(base) root@MSI:/mnt/CirGO/Py3+/CirGO_Wind_Unix# python CirGO.py -h
Traceback (most recent call last):
  File "CirGO.py", line 55, in <module>
    import CirGOVisualGO
  File "/mnt/c/Users/theab/Documents/CirGO/Py3+/CirGO_Wind_Unix/CirGOVisualGO.py", line 42, in <module>
    mpl.use("TkAgg")           #  MacOS so it sees Py as a framework
  File "/root/anaconda3/lib/python3.8/site-packages/matplotlib/__init__.py", line 1078, in use
    plt.switch_backend(name)
  File "/root/anaconda3/lib/python3.8/site-packages/matplotlib/pyplot.py", line 285, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

**Comment by babramso** [comment]
I followed the "windows" instructions under the Py2 git page.  Works like a charm
